// import './1.js';
// import './2.js';
// import './3.js';
// import './4.js';
// import './5.js';
// import './6.js';
//? import './7.js';
import './7(2).js';
// import './8.js';
// import './9.js';
//? import './10.js';